= Advanced DB Custom Metrics
:description: Extension for AppDynamics to collect Custom Database Metrics 
:url-repo: https://github.com/bfrevel/advanced-db-custom-metrics
:toc:

== Use case

Standart AppDynamics DB Custom Metrics have some typical metric limitations like:

* It's not possible to collect metrics from the past
* It's not possible to use analytics features for custom metrics.
* It's not possible to compare timeframes.
* High maintenance effort required when collecting metrics for different shops and products

This extension reads the data from the database every minute and sends the information to AppDynamics Analytics Event API. 


== Installation

Clone this repository to your environment.

== Configuration

=== Create Event Schema in AppDynamics

doc: https://docs.appdynamics.com/appd/24.x/latest/en/extend-cisco-appdynamics/cisco-appdynamics-apis/analytics-events-api#id-.AnalyticsEventsAPIv24.3-create_schemaCreateEventSchema

[source]
----
POST http://analytics.api.example.com/events/schema/<schemaName> HTTP/1.1
X-Events-API-AccountName:<global_account_name>
X-Events-API-Key:<api_key>
Content-Type: application/vnd.appd.events+json;v=2
Accept: application/vnd.appd.events+json;v=2
{
    "schema": {
        "Shop": "String",
        "Product": "String",
        "Option": "String",
        "Sales": "Integer"
    }
}
----

[IMPORTANT]
====
* The API user needs the permission to manage Custom Analytics Events Schemas.
* The column names must match with the column names of the sql result, which will be executed. 
====

=== Configure Python environment

[source, sh]
----
python<version> -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
----

=== Configure application properties

.Properties
[%autowidth, cols="1m,1m,1"]
|===
|section |property |description

|app
|timerange_historial_data_in_min
|During each start, the extension initially checks the Events API for missing historical data, requests them from the database and publishes the data to the Events API. 

The value is the timerange in minutes, the extension will synchronize historical data.

`default = 1440`

|
|filters
a|This is a list of Name/Values pairs, which is used to identify the data, you want to send to AppDynamics Events API. 

[source, json]
----
{
    "Name":"Product", 
    "Values": [
        "Mobile1", 
        "Mobile2"
    ]
}
----

The name must match with the placeholder in `database/query`. The extension replaces the Values with the placeholder during execution. 

|appdynamics-api
|url
|Your Analytics URL. Check https://docs.appdynamics.com/paa/en/cisco-appdynamics-saas-domains-and-ip-ranges for saas instances. 

|
|account_name
|AppDynamics Global Account Name. Check on your Controller / Licenses. 

|
|key
a|Key of the API user.

IMPORTANT: The API user needs the permission to query and publish events to the Custom Analytics Events Schemas, defined in `appdynamics-api.schema`

|
|schema
a|Target Schema, to which the information will get published. 


|database
|url
|Database to use. `localhost/free` during tests for example. 

|
|user
|Database user. This user needs read permission to the table/view, defined in `database.query`.

|
|password
|Database password

|
|query
a|This query will get executed once a minute. The extension will send the result to the AppDynamics Analytics Events API. This example collects all sales data for the different Shops/Products/Options for the last (completed) minute. 

[IMPORTANT]
====
* The first column of the result must be a `Date`, which will be used as EventTimestamp in AppDynamics.
* All other column names must match to the names used in the AppDynamics Events API Schema (`appdynamics-api.schema`).
* The placeholders in the `WHERE` clause must match the `app.filter` Names. 
* Use `in` instead of `=`. Otherwise the filtering would only work, if you define only one value in `app.filter`.
* The `:interval` is required in the query to get the data for the last *interval* minutes. 
====


|===

.Create property file
[source, sh]
----
cat <<EOT > config.ini
[app]
timerange_historial_data_in_min = 1440
filters = [{"Name":"Shop", "Values": ["OnlineShop"]}, {"Name":"Product", "Values": ["Product_1", "Product_2", "Product_3"]}, {"Name":"Option", "Values": ["Option_A"]}]

[appdynamics-api]
url = https://<analytics-api-url>.saas.appdynamics.com
account_name = <global_account_name>
key = <api-key>
schema = <analytics-events-schema>

[database]
dsn = <db-url>
user = <db-user>
pw = <db-password>
query = 
    SELECT
        TRUNC (SALEDATE, 'mi') "EVENT_TIMESTAMP",
        SHOP                   "SHOP",
        PRODUCT                "PRODUCT",
        PRODUCT_PACKAGE        "OPTION",
        COUNT(*)               "SALES"
    FROM
        SALESDATA
    WHERE
        SHOP in ({Shop})
        AND PRODUCT in ({Product})
        AND PACKAGE_TYPE in ({Option})
        AND SALEDATE BETWEEN TRUNC (SYSDATE, 'mi') - (:interval/1440) AND TRUNC (SYSDATE, 'mi') - INTERVAL '0.001' SECOND
    GROUP BY SHOP, PRODUCT, PACKAGE_TYPE, EVENT_TIMESTAMP
    ORDER BY EVENT_TIMESTAMP, PRODUCT
EOT
----



== Functionality

=== Initial execution

After starting the application, it will schedule a inital data load to transfer historical data to the AppDynamics Controller, if they're not available yet. 

. For each combination of `app.filter`, the application will check the latest available data in AppDynamics Analytics.
. The application executes the query `database.query`, but for the interval defined in `timerange_historial_data_in_min`, instead of the last minute. 
. In the next step, the application filter for data, which is not already available in AppDynamics Analytics (comparing `event_timestamp`) and send send them to the AppDynamics Analytics Events API.

NOTE: This precedure enables to you add additional filter values in the future. 

.Example

. The application will send the following query to the AppDynamics Analytics Events API, when using the example properties from above
+
[source, sql]
----
SELECT Shop, Product, Option, max(eventTimestamp) FROM <analytics-events-schema> WHERE eventTimestamp >= <now - timerange_historial_data_in_min>
----
+ 
The result could be this. Product 1 and 2 are available. But with `eventTimestamp` from 2min ago. Product 3 is not available, as it just got added to the list. 
+
[cols="1,1,1,1"]
|===
|SHOP |PRODUCT |OPTION |EVENT_TIMESTAMP

|OnlineShop
|Product_1
|Option_A
|2024-03-27 12:39:00

|OnlineShop
|Product_2
|Option_A
|2024-03-27 12:39:00
|===

. This is the database query which will get executed, when using the config example from above. 
+
[source, sql]
----
SELECT
    TRUNC (SALEDATE, 'mi') "EVENT_TIMESTAMP",
    SHOP                   "SHOP",
    PRODUCT                "PRODUCT",
    PRODUCT_PACKAGE        "OPTION",
    COUNT(*)               "SALES"
FROM
    SALESDATA
WHERE
    SHOP in ('OnlineShop')
    AND PRODUCT in ('Product_1', 'Product_2', 'Product_3')
    AND PACKAGE_TYPE in ('Option_A')
    AND SALEDATE BETWEEN TRUNC (SYSDATE, 'mi') - (1440/1440) AND TRUNC (SYSDATE, 'mi') - INTERVAL '0.001' SECOND
GROUP BY SHOP, PRODUCT, PACKAGE_TYPE, EVENT_TIMESTAMP
ORDER BY EVENT_TIMESTAMP, PRODUCT
----
+
The result could look like this, when being executed at 2024-03-27 12:42:
+
[cols="1,1,1,1,1"]
|===
|EVENT_TIMESTAMP |SHOP |PRODUCT |OPTION |SALES

|2024-03-27 12:41:00
|OnlineShop
|Product_1
|Option_A
|3

|2024-03-27 12:40:00
|OnlineShop
|Product_1
|Option_A
|5

|2024-03-27 12:39:00
|OnlineShop
|Product_1
|Option_A
|5

|2024-03-27 12:38:00
|OnlineShop
|Product_1
|Option_A
|2

| < 2024-03-27 12:38:00
|OnlineShop
|Product_1
|Option_A
|...

|2024-03-27 12:41:00
|OnlineShop
|Product_2
|Option_A
|13

|2024-03-27 12:40:00
|OnlineShop
|Product_2
|Option_A
|15

|2024-03-27 12:39:00
|OnlineShop
|Product_2
|Option_A
|29

|2024-03-27 12:38:00
|OnlineShop
|Product_2
|Option_A
|15

| < 2024-03-27 12:38:00
|OnlineShop
|Product_2
|Option_A
|...


|2024-03-27 12:41:00
|OnlineShop
|Product_3
|Option_A
|2

|2024-03-27 12:40:00
|OnlineShop
|Product_3
|Option_A
|1

|2024-03-27 12:39:00
|OnlineShop
|Product_3
|Option_A
|4

|2024-03-27 12:38:00
|OnlineShop
|Product_3
|Option_A
|0

| < 2024-03-27 12:38:00
|OnlineShop
|Product_3
|Option_A
|...
|===

. Now all data will get filtered and sent to AppDynamics Analytics Events API
+
[cols="1,1,1,1,1"]
|===
|EVENT_TIMESTAMP |SHOP |PRODUCT |OPTION |SALES

|2024-03-27 12:41:00
|OnlineShop
|Product_1
|Option_A
|3

|2024-03-27 12:40:00
|OnlineShop
|Product_1
|Option_A
|5

|2024-03-27 12:41:00
|OnlineShop
|Product_2
|Option_A
|13

|2024-03-27 12:40:00
|OnlineShop
|Product_2
|Option_A
|15

|2024-03-27 12:41:00
|OnlineShop
|Product_3
|Option_A
|2

|2024-03-27 12:40:00
|OnlineShop
|Product_3
|Option_A
|1

|2024-03-27 12:39:00
|OnlineShop
|Product_3
|Option_A
|4

|2024-03-27 12:38:00
|OnlineShop
|Product_3
|Option_A
|0

| < 2024-03-27 12:38:00
|OnlineShop
|Product_3
|Option_A
|...
|===
+
NOTE: All data, older than `2024-03-27 12:39:00` for Products 1 and 2 have been removed. Product 3 was just added, so all data sets will be sent to AppDynamics Analytics Events API.


=== Continuous execution

Once the initial import is completed after startup, the application will schedule a job to synchronize data from the database to AppDynamics Analytics. This job will be scheduled to execute once every minute.

. The application executes the query `database.query` for the last minute.
. The result will be sent to AppDynamics Analytics Events API.


.Example

. This is the database query which will get executed, when using the config example from above.
+ 
[source, sql]
----
SELECT
    TRUNC (SALEDATE, 'mi') "EVENT_TIMESTAMP",
    SHOP                   "SHOP",
    PRODUCT                "PRODUCT",
    PRODUCT_PACKAGE        "OPTION",
    COUNT(*)               "SALES"
FROM
    SALESDATA
WHERE
    SHOP in ('OnlineShop')
    AND PRODUCT in ('Product_1', 'Product_2', 'Product_3')
    AND PACKAGE_TYPE in ('Option_A')
    AND SALEDATE BETWEEN TRUNC (SYSDATE, 'mi') - (1/1440) AND TRUNC (SYSDATE, 'mi') - INTERVAL '0.001' SECOND
GROUP BY SHOP, PRODUCT, PACKAGE_TYPE, EVENT_TIMESTAMP
ORDER BY EVENT_TIMESTAMP, PRODUCT
----

. The result could look like this, when being executed at 2024-03-27 12:43:
+
[cols="1,1,1,1,1"]
|===
|EVENT_TIMESTAMP |SHOP |PRODUCT |OPTION |SALES

|2024-03-27 12:42:00
|OnlineShop
|Product_1
|Option_A
|4

|2024-03-27 12:42:00
|OnlineShop
|Mobile_2
|Option_A
|12

|2024-03-27 12:42:00
|OnlineShop
|Mobile_3
|Option_A
|1
|===
+
This result will get sent to the AppDynamics Analytics Events API, by using the same column names. 


== Execute the extension

.Run
[source, sh]
----
.venv/bin/python advanced-db-custom-metrics.py
----